FROM ubuntu:16.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y -qq
ENV ROOT_SQL_PASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
ENV CURUSER=$(whoami)
RUN echo "Etc/UTC" |  tee -a /etc/timezone
RUN rm -rf /etc/localtime
RUN ln -s /usr/share/zoneinfo/Zulu /etc/localtime
RUN apt-get install -y -qq tzdata
RUN dpkg-reconfigure -f noninteractive tzdata
RUN debconf-set-selections <<< "mysql-server mysql-server/root_password password $ROOT_SQL_PASS"
RUN debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $ROOT_SQL_PASS"
RUN echo -e "[client]\nuser=root\npassword=$ROOT_SQL_PASS" | tee /root/.my.cnf
RUN apt-get -y -qq install git python-virtualenv python3-virtualenv curl ntp build-essential screen cmake pkg-config libboost-all-dev libevent-dev libunbound-dev libminiupnpc-dev libunwind8-dev liblzma-dev libldns-dev libexpat1-dev libgtest-dev mysql-server lmdb-utils libzmq3-dev
RUN cd /usr/src/gtest &&\
        cmake . &&\
        make &&\
        mv libg* /usr/lib/



 