FROM ubuntu:17.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq
RUN apt-get install -y -qq software-properties-common git build-essential cmake cmake-curses-gui libuv1-dev libmicrohttpd-dev