FROM ubuntu:16.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq
RUN apt-get install -y -qq nvidia-cuda-dev nvidia-cuda-toolkit libmicrohttpd-dev libssl-dev clang cmake cmake-curses-gui libssl-dev build-essential software-properties-common
RUN add-apt-repository ppa:jonathonf/gcc-7.1
RUN apt-get update -qq
RUN apt-get install -y -qq  gcc-7 g++-7
ENV CC=/usr/bin/clang
ENV CXX=/usr/bin/clang++
