FROM ubuntu:16.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq
RUN apt-get install -y -qq software-properties-common git doxygen cmake cmake-curses-gui golang build-essential libssl-dev pkg-config libboost-all-dev libcap2-bin
