FROM ubuntu:16.04
WORKDIR /xmr-stak-cpu
RUN apt update -qq
RUN apt install -y -qq git curl wget
RUN apt install -y -qq libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev

RUN git clone https://github.com/rafalsladek/xmr-stak-cpu.git /xmr-stak-cpu
RUN cd /xmr-stak-cpu
RUN cmake -DCMAKE_LINK_STATIC=ON .
RUN make install
RUN mv /xmr-stak-cpu/bin/xmr-stak-cpu xmr-stak-cpu_ubuntu_16.04
RUN git -C /xmr-stak-cpu clean -fd
RUN ls -al
